show_excerpts: true # set to true to show excerpts on the homepage
sass:
  sass_dir: _sass

texture:
  title: Thorn
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: soonthornpen
    rss: rss
  style: black
  showNav: true
  navigation:
    - title: Home
      url: "/"
    - title: My Work
      url: "/my-work"

plugins:
  - jekyll-seo-tag
#  - jekyll-feed
