texture:
  title: Thorn
  tagline: Developer. Designer
  date_format: "%b %-d, %Y"

  social_links:
    twitter: soonthornpen
  style: black
  showNav: true
  navigation:
    - title: Home
      url: "/"
    - title: My Work
      url: "/my-work"

remote_theme: samarsault/texture
